name: Setup Tools

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  setup:
    name: Install Required Tools
    runs-on: azdev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git for authentication
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip nodejs npm  

      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
