name: Terraform Apply

on:
  workflow_call:

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: self-hosted

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'schedule')
        run: terraform apply -auto-approve -input=false
