name: Terraform

on:
  workflow_call:
    inputs:
      AZURE_BACKEND_STATE_FILE:
        required: true
        type: string
      AZURE_BACKEND_RESOURCE_GROUP_NAME:
        type: string
        required: true
      AZURE_BACKEND_STORAGE_ACCOUNT_NAME:
        type: string
        required: true
      AZURE_BACKEND_CONTAINER_NAME:
        type: string
        required: true
      GH_RUNNER_POOL:
        required: false
        default: rdam
        type: string

    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      GH_TOKEN:
        required: true

jobs:
  plan:
    name: Terraform Plan + Checks
    runs-on: ${{ inputs.GH_RUNNER_POOL }}
    environment: production
    env:
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure git auth for private modules (.netrc)
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -euo pipefail

          cat > ~/.netrc <<EOF
          machine github.com
          login x-access-token
          password ${GH_TOKEN}
          EOF

          chmod 600 ~/.netrc

          # Disable interactive prompts
          git config --global credential.helper ""
          export GIT_TERMINAL_PROMPT=0

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -backend-config="resource_group_name=${{ inputs.AZURE_BACKEND_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ inputs.AZURE_BACKEND_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ inputs.AZURE_BACKEND_CONTAINER_NAME }}" \
            -backend-config="key=${{ inputs.AZURE_BACKEND_STATE_FILE }}" \
            -backend-config="use_azuread_auth=true"

      - name: Terraform Import Virtual Hub Connections
        run: |
          terraform import 'azurerm_virtual_hub_connection.vnet_connections["VNET_AZDEV_LZ_Management-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/VNET_AZDEV_LZ_Management-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["azdev01-vnet-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/azdev01-vnet-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["VNCWVBS001-vnet-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/VNCWVBS001-vnet-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["vnet-azdev-sql-beheer-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/vnet-azdev-sql-beheer-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["vnet-rdam-tbms-tst-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/vnet-rdam-tbms-tst-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["vnet-azdev-identity-tst-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/vnet-azdev-identity-tst-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["vnet-azdev-linux-ont-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/vnet-azdev-linux-ont-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["vnet-azdev-terraform-alg-sbx-001-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/vnet-azdev-terraform-alg-sbx-001-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["vnet-azdev-hip-apim-poc-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/vnet-azdev-hip-apim-poc-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["vnet-azdev-netwerkbeheer-tst-002-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/vnet-azdev-netwerkbeheer-tst-002-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["vnet-azdev-patrick-tst02-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/vnet-azdev-patrick-tst02-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["vnet-azdev-connectivity-terraformtest-001-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/vnet-azdev-connectivity-terraformtest-001-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["VNET_Rdam_PF_Connectivity_Hub-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/VNET_Rdam_PF_Connectivity_Hub-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["vnet-azdev-netwerkbeheer-tst-001-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/vnet-azdev-netwerkbeheer-tst-001-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["VNET_AZDEV_Shared_Resources-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/VNET_AZDEV_Shared_Resources-link'

          terraform import 'azurerm_virtual_hub_connection.vnet_connections["VNET_New_Resources-link"]' \
          '/subscriptions/69e07918-e789-4249-ba3d-957a716c36d2/resourceGroups/rg-azdev-connectivity-tst-weu-01-hub/providers/Microsoft.Network/virtualHubs/vhub-azdev-connectivity-tst-weu-01/hubVirtualNetworkConnections/VNET_New_Resources-link'
      
      - name: Terraform Format
        run: terraform fmt -check

      # Validate
      - name: Terraform Validate
        run: terraform validate -no-color

      # TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint Init
        run: tflint --init

      - name: TFLint
        run: tflint -f compact --minimum-failure-severity=error


      # tfsec (security scan)
      - name: Run tfsec
        shell: bash
        run: |
          tfsec . || true



      # Saved plan (voor apply zonder re-plan)
      - name: Terraform Plan
        id: tf-plan
        if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'schedule'
        run: |
          terraform plan -input=false -out=tfplan
          terraform show -no-color tfplan | tee plan_output.log
          terraform show -json tfplan > tfplan.json

      - name: Prevent Destroy (Scheduled Runs Only)
        if: github.event_name == 'schedule'
        run: |
          if jq -e '.resource_changes[] | select(.change.actions[] == "delete" or .change.actions[] == "destroy")' tfplan.json > /dev/null; then
            echo "Destroy operation detected."
            exit 1
          else
            echo "No destroy operations detected."
          fi

      # Upload artifacts zodat apply job exact dit plan kan gebruiken
      - name: Upload plan artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tfplan-${{ github.run_id }}
          path: |
            tfplan
            plan_output.log
            tfplan.json

  apply:
    name: Terraform Apply (requires approval)
    runs-on: ${{ inputs.GH_RUNNER_POOL }}
    needs: plan
    environment: production

    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'schedule')
    env:
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ inputs.AZURE_BACKEND_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ inputs.AZURE_BACKEND_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ inputs.AZURE_BACKEND_CONTAINER_NAME }}" \
            -backend-config="key=${{ inputs.AZURE_BACKEND_STATE_FILE }}" \
            -backend-config="use_azuread_auth=true"

      - name: Download plan artifacts
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ github.run_id }}

      - name: Terraform Apply (uses saved plan)
        run: |
          terraform apply -auto-approve -input=false tfplan
